### ISSUE TITLE
fingerprinting mitigations for multi-screen window placement

### ISSUE THREAD

**Issue by samuelweiler** [w3c/secondscreen-charter#26]
I'm concerned about the possibility of fingerprinting surface being exposed by the new Multi-Screen Window Placement API, since relative display position seems like it changes infrequently in many contexts.

What can be done to minimize that risk?  Are there technical measures we can introduce beyond just permissions?

The WG success criteria include "Specifications should also avoid unnecessary or severe increases to fingerprinting surface, especially for passive fingerprinting.", so this is not a blocking comment, but I wonder if the WG will be able to succeed at meeting this criteria in Multi-Screen Window Placement.

**Comment by anssiko** [comment]
@samuelweiler thanks for your comment. I think the responses to the W3C Security and Privacy Self-Review Questionnaire may answer (some of) your questions:

https://github.com/webscreens/window-placement/blob/main/security_and_privacy.md

See also the explainer and its Security & Privacy section:

https://github.com/webscreens/window-placement/blob/main/EXPLAINER.md#privacy--security

**Comment by pes10k** [comment]
Thank you @anssiko for those links.  After reading through them, I appreciate the group's thoroughness, but I'm still concerned that the baseline envisioned by the charter and the window-placement spec seem to assume that extra fingerprinting surface is unavoidable (and so, presumably, that the group would not prioritize exploring ways of removing the additional passive fingerprinting surface).

I suggest the group slightly rework the proposed charter to include as explicit goals, i) not adding additional passive fingerprinting surface, and ii) minimizing the granularity of the fingerprinting surface exposed for users who take advantage of the new functionality defined by the group

**Comment by michaelwasserman** [comment]
Thank you, @samuelweiler and @pes10k for your comments. We wish to minimize fingerprinting surfaces while providing a useful multi-screen API for window placement. Please let me try to respond to your concerns:

> relative display position seems like it changes infrequently in many contexts ... What can be done to minimize that risk? Are there technical measures we can introduce beyond just permissions?

There are several use cases for carefully exposing the relative placement of displays:
- Understanding display layouts to align content over multiple screens (e.g. video walls, multi-screen gaming, etc.).
- Compatibility with pre-existing window.screen information about the available region of the window's current screen.
- Extending pre-existing window.open(), moveTo(), etc. APIs for placing windows in multi-screen environments.

Gating access with a permission minimizes surreptitious fingerprinting, and we are open to suggestions of other technical measures! Perhaps some UAs or WMs may implement a subset of these APIs without coordinate-based features (i.e. just for cross-screen fullscreen requests), or map coordinates to lower-granularity or obfuscated spaces (if that's compatible with existing definitions). Future work may also pursue placement of windows on target displays without specific coordinates nor knowledge about relative display arrangements, but use cases for that seem limited.

> prioritize exploring ways of removing the additional passive fingerprinting surface

The un-gated window.screen.isExtended bit provides the minimal fingerprinting surface to unobtrusively determine whether requesting multi-screen information would be useful or not, so sites may avoid prompting users for inapplicable information. Our privacy partners concluded that the amount of entropy is far less than one bit, since the population of multi-screen devices is relatively low. Perhaps some UAs may implement the remainder of the API without exposing this one bit, or provide a static value for all devices.

The un-gated window.screen.onchange event simply obviates the need for sites to poll the Screen API for the same effect. We additionally seek UA implementation parity and clearer definitions for left|top|availLeft|availTop Screen members.

We feel that the proposed API strikes a good balance of utility and privacy, and welcome additional thoughtful feedback and guidance. Thank you again for engaging on these topics, we hope continued discussion here will help refine the proposal!

**Comment by pes10k** [comment]
Thank you for your follow up @michaelwasserman .  My request is still to amend the charter to "prioritize exploring ways of removing the additional passive fingerprinting surface".

I dont think we need to debate or sort out the best implementation of the APIs the WG will be working on right now (though I'll note that "does the user have uncommon hardware" is a very distinguishing single bit of information for fingerprinters; all identifying bits aren't created equal), but the request is just to make sure the WG doesn't start from the assumption that "adding fingerprinting bits will pass privacy review."

Not that thats necessarily _not_ the case either; i just don't want the WG start from that possibly-incorrect presumption.

**Comment by npdoty** [comment]
Just following up on this post-holidays: I see there was some discussion / brainstorming about the particular API design here, but also some specific requests about including (or not excluding) goals in the charter. Can we get an update on whether the charter can be edited as suggested?

👍🏻 that there will be more to review about particular designs after the group is re-chartered.

**Comment by tidoust** [comment]
The draft charter has not been updated. Before I integrate the suggested update, I would like to understand it.

Specifically, I do not understand why the proposal triggers *passive* fingerprinting concerns. I interpret the term as defined in the [Mitigating Browser Fingerprinting](https://www.w3.org/TR/fingerprinting-guidance/#dfn-passive-fingerprinting) guidelines. As far as I can tell, the Multi-Screen Window Placement proposal neither introduces nor plans to introduce "characteristics observable in the contents of Web requests, without the use of any code executed on the client". Am I missing something?

It seems good to emphasize that additional passive fingerprinting surface needs to be avoided. The proposed charter already has the following explicit text in its success criteria section for all of its specs:
"Each specification should contain separate sections detailing all known security and privacy implications for implementers, Web authors, and end users. Specifically, the user must always be in control of privacy-sensitive information that may be conveyed through the APIs, such as the visibility or access to presentation displays, or the URLs of the web content to be presented. *Specifications should also avoid unnecessary or severe increases to fingerprinting surface, especially for passive fingerprinting*."

The suggested update seems like a reformulation of the last sentence. Could you clarify how it improves the current text from your perspective?

**Comment by npdoty** [comment]
I think maybe the concern (raised by Sam and Pete in this thread) was that the current language might be read to imply that increased fingerprinting surface was inevitable and definitely acceptable.

Maybe _Specifications should minimize and mitigate fingerprinting surface._ would be simpler.

(Yes, that is the definition of "passive fingerprinting", though that term does occasionally get used in lots of different senses. I haven't reviewed the specs in detail yet and generally thought that would come later in our process than the charter.)

**Comment by tidoust** [comment]
Simplification works for me! I prepared PR #30 accordingly.

**Comment by tidoust** [comment]
Text suggested by @npdoty has now been integrated in the draft charter, see [success criteria section](https://w3c.github.io/secondscreen-charter/#success-criteria)

@samuelweiler, @pes10k Can you confirm that this addresses your concerns? (with a shared understanding that there will be discussions on fingerprinting surface)

**Comment by pes10k** [comment]
that looks good to me.  Thanks everyone!

**Comment by samuelweiler** [comment]
My concern was not about the charter language - I wasn't blocking the charter.  I was concerned that the WG would not succeed at mitigation the FP surface with this work item.  I'm glad to hear discussion of a path toward that.  No objection to the charter moving fwd.
